### ISSUE TITLE
What format is Start and End date time supposed to be in?

### ISSUE THREAD

**Issue by xpluscal** [ebarooni/capacitor-calendar#104]
Documentation states "number" - is that unix timestamp?

Thx! awesome plugin!

**Comment by ebarooni** [comment]
Hey @xpluscal, yep its unix timestamp. Check in the inline docs of the method, there is probably and example using `startDate` and `endDate`. Best is to look it up in the `./definitions.ts` file.

Short example:
```
const startDate = Date.now()
```
