### ISSUE TITLE
Error creating new calendar

### ISSUE THREAD

**Issue by iamandreadompe** [ebarooni/capacitor-calendar#105]
Hello to everyone!

i'm trying to create a new calendar on my iPhone

i do this

`const permissionResults = await CapacitorCalendar.requestAllPermissions();`

Permission results {"readCalendar":"granted","writeReminders":"granted","readReminders":"granted","writeCalendar":"granted"}

```
    async createCalendar() {
        try {
            const response: any = await CapacitorCalendar.createCalendar({
                title: this.newCalendarName,
                color: "#FF0000",
            });
            await this.loadCalendars();
            this.selectedCalendar = this.calendars.filter(calendar => calendar.id === response.result)[0];
            this.newCalendarName = ''; // Reset the input field
        } catch (error) {
            console.error('Error creating calendar', JSON.stringify(error) + 'calendar name: ' + this.newCalendarName);
        }
    }
```
    
i get this error

```
Failed to save calendar: Error Domain=EKErrorDomain Code=17 "That account does not allow calendars to be added or removed." UserInfo={NSLocalizedDescription=That account does not allow calendars to be added or removed.}
{"message":"[CapacitorCalendar.createCalendar(_:)] Could not create calendar","errorMessage":"[CapacitorCalendar.createCalendar(_:)] Could not create calendar"}
```

**UPDATE**

I didn't have any calendars on my iphone, i've just few calendars with google calendars, so i've tried to create manually a new calendar "Test" and in the Calendars Options inside iphone i set "TEST" as the default calendar  (create manually on iPhone)
now i can create all the calendars i want....

i think there is a sort of default calendar system, i think before with the google as default calendar
the plugin was trying to create the calendar on Google, because a calendar I had on Google was set as the default calendar.

How can we prevent this situation?

If by chance a user is in the same situation as me, i.e. with the default calendar on Google are we screwed?

**Comment by aparajita** [comment]
@ebarooni  Looks like the EKSource has to be specified. Here's what Claude said:

To create a calendar synced to iCloud in iOS, you'll want to use the iCloud source when creating an EKCalendar. Here's how you can do it:

1. First, you need to get the iCloud source from the available sources in the EventKit framework.
2. Then, you can use this source to create a new EKCalendar.

Here's a code snippet that demonstrates this process:

```swift
import EventKit

let eventStore = EKEventStore()

// Request access to the calendar
eventStore.requestAccess(to: .event) { (granted, error) in
    if granted {
        // Get all sources
        let sources = eventStore.sources

        // Find the iCloud source
        if let iCloudSource = sources.first(where: { $0.sourceType == .calDAV && $0.title == "iCloud" }) {
            // Create a new calendar using the iCloud source
            let newCalendar = EKCalendar(for: .event, source: iCloudSource)
            newCalendar.title = "My New iCloud Calendar"
            
            // Save the calendar
            do {
                try eventStore.saveCalendar(newCalendar, commit: true)
                print("Calendar created and synced to iCloud successfully")
            } catch {
                print("Error saving calendar: \(error.localizedDescription)")
            }
        } else {
            print("iCloud source not found")
        }
    } else {
        print("Access to calendar not granted")
    }
}
```

This code does the following:

1. It creates an `EKEventStore` instance.
2. It requests access to the calendar.
3. If access is granted, it retrieves all available sources.
4. It searches for the iCloud source, which typically has a `sourceType` of `.calDAV` and a `title` of "iCloud".
5. If the iCloud source is found, it creates a new `EKCalendar` using this source.
6. Finally, it saves the new calendar, which will sync it to iCloud.

Remember that the user needs to be signed into their iCloud account on the device for this to work. Also, make sure to handle any potential errors, such as the iCloud source not being available or permissions not being granted.

Would you like me to explain any part of this code in more detail?

**Comment by ebarooni** [comment]
Thanks @iamandreadompe and @aparajita for the clarifications. I will include this for the next release.

**Comment by iamandreadompe** [comment]
@ebarooni 
i think it would be useful if there was a function to set the default calendar (via id) in case there isn't one by default
something like that
`await CapacitorCalendar.setDefault(calendar.id)`
