### ISSUE TITLE
change implementation "androidx.core:core-ktx:+" to a specific version

### ISSUE THREAD

**Issue by 5uper** [ebarooni/capacitor-calendar#106]
The following line leads to the following error when compiling in Android.

https://github.com/ebarooni/capacitor-calendar/blob/aa8db9195c5b330619b0d2a55b095a251e6669be/android/build.gradle#L60

> An issue was found when checking AAR metadata:
> 
> Dependency 'androidx.core:core:1.15.0-alpha01' requires libraries and applications that
> depend on it to compile against version 35 or later of the
> Android APIs.
> 
> :app is currently compiled against android-34.
> 
> Also, the maximum recommended compile SDK version for Android Gradle
> plugin 8.2.1 is 34.
> ...

The value `androidx.core:core-ktx:+` causes `androidx.core:core:1.15.0-alpha01` to be used.

https://androidx.tech/artifacts/core/core-ktx/

It would be nice if we could use a specific LTS version here `androidx.core:core:1.13.1`, Android SDK 35 is still in dev state.

**Comment by muhammadosmanali** [comment]
facing the same issue.

**Comment by ebarooni** [comment]
@5uper @muhammadosmanali Hi both, I will include this in the next release.

**Comment by muhammadosmanali** [comment]
Ok Thank you @ebarooni

**Comment by muhammadosmanali** [comment]
Hi, @5uper , until then i have workaround, you can this code in android -> app -> build.gradle

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'androidx.core' && details.requested.name == 'core') {
            details.useVersion '1.13.1'
            details.because 'Add the Reason here'
        }
    }
}

**Comment by aparajita** [comment]
@ebarooni Android Studio tries to warn us against doing things we will regret. It highlights that dependency with a yellow warning underline, and hovering over it reveals the message:

`Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds`
