### ISSUE TITLE
Set default calendar

### ISSUE THREAD

**Issue by iamandreadompe** [ebarooni/capacitor-calendar#107]
@ebarooni  
i think it would be useful if there was a function to set the default calendar (via id) in case there isn't one by default
something like that
`await CapacitorCalendar.setDefault(calendar.id)`

This is related to #105 

If in my iphone i don't have a default calendar or i have another calendar as default calendar i can't sync my events 

_Originally posted by @iamandreadompe in https://github.com/ebarooni/capacitor-calendar/issues/105#issuecomment-2202161623_

**Comment by iamandreadompe** [comment]
Closed because I don't think it can be done with EventKit

**Comment by iamandreadompe** [comment]
@ebarooni you think is it possibile?

Because chatGPT says 
`EventKit does not provide a direct method to set a default calendar for new events. The default calendar setting is managed by the user settings in the iOS Calendar app.`

**Comment by ebarooni** [comment]
@iamandreadompe I was looking into it. I think Its not possible.
