### ISSUE TITLE
Android: createEventWithPrompt without permissions

### ISSUE THREAD

**Issue by theigl** [ebarooni/capacitor-calendar#134]
Hi @ebarooni,

Thanks a lot for this great plugin! In our app, we only have a single use-case of adding events to the users calendars. For this, we use `createEventWithPrompt`.

On iOS this does not require any permissions. 
On Android, the current implementation needs `READ_CALENDAR` permission. This should not be necessary.

The problem is the following line:
https://github.com/ebarooni/capacitor-calendar/blob/469e0827577ab72e6a63933b5d0dff7d0db298c7/android/src/main/java/dev/barooni/capacitor/calendar/CapacitorCalendarPlugin.kt#L49

If we comment it out, everything works as expected. The app requires no permissions and the user can add events to their calendar. If I understand it correctly, the only downside is that we cannot retrieve the resulting event IDs.

Could you wrap `fetchCalendarEventIDs` in a try/catch or return an empty array of event IDs if no permission has been granted?

**Comment by ebarooni** [comment]
Hi @theigl , thanks for the suggestion! I will think about it a bit and will probably provide a way to have the ability to opt out of receiving the id of the generated event in exchange of not having to request read access to the calendar.

**Comment by theigl** [comment]
Thanks a lot @ebarooni! 🙏
