### ISSUE TITLE
Support deleteCalendar on Android

### ISSUE THREAD

**Issue by vlad31011** [ebarooni/capacitor-calendar#138]
looks like now there are no way to delete calendar event on Android platform. 
<img width="593" alt="Screenshot 2024-09-20 at 06 59 42" src="https://github.com/user-attachments/assets/a71c4238-6ab0-4e11-b177-86de6e69f406">

**Comment by ebarooni** [comment]
The title and the description are a bit confusing. Do you mean to support deleting events on android? This is already supported and the support was never dropped. 

But the screenshot is showing the `deleteCalendar` method which is used to delete a **calendar** on iOS and it was never supported on android (as far as i know it also cant be supported).

**Comment by vlad31011** [comment]
ok, then my question is how to delete calendar event on Android device?
I create calendar event based on `createEventWithPrompt` method, on ios I can remove that event based on `deleteCalendar` method, but that method doesn't work on Android, so do we have any alternative method for Android to delete calendar event? @ebarooni

**Comment by vlad31011** [comment]
oh I see there is `deleteEventsById` method exist, I will try it, sorry :)
