### ISSUE TITLE
Add support for Capacitor 6

### ISSUE THREAD

**Issue by ebarooni** [ebarooni/capacitor-calendar#56]

**Comment by aparajita** [comment]
I just went through the process of updating to Capacitor 6 and Ionic 8. Use the scripts they provide and it's fairly painless.

This is a blocker for me, hope you can prioritize this.

**Comment by ebarooni** [comment]
@aparajita Sure. I will adapt the timeline and prioritize this.

**Comment by ebarooni** [comment]
@aparajita I decided to match the major version of capacitor. v6.* has support for capacitor 6 and v5.* for capacitor 5. I will try to keep the support for capacitor 5 as long as possible.
