### ISSUE TITLE
Feature request - Create event with prompt but with options

### ISSUE THREAD

**Issue by peter1599** [ebarooni/capacitor-calendar#68]
Hello.

It's really good to have a working calendar plugin for capacitor.

You literally saved an app. I just refactored an application from angular to react and the calendar plugin used in angular version of the app was not compatible with react. So thank you for maintaining this.

I don't know if its me but i would really like to see a createEventWithPrompt but with options like (title, location, startDate, endDate, allDay etc...)

**Comment by inpt333** [comment]
Hey @ebarooni , thanks for implementing this feature and releasing v6.1.0. It partially works for me in Android. The title is set properly, but the `startDate`, `endDate` and `isAllDay` are not properly applied, and I think the issue is that you're using the wrong Intent extras. These worked for me:

<img width="764" alt="image" src="https://github.com/ebarooni/capacitor-calendar/assets/6491485/f3dfc1d8-32b3-4f8a-a42e-ccee6fb1ade5">

**Comment by inpt333** [comment]
> Hey @ebarooni , thanks for implementing this feature and releasing v6.1.0. It partially works for me in Android. The title is set properly, but the `startDate`, `endDate` and `isAllDay` are not properly applied, and I think the issue is that you're using the wrong Intent extras. These worked for me:
> 
> <img alt="image" width="764" src="https://private-user-images.githubusercontent.com/6491485/327351305-f3dfc1d8-32b3-4f8a-a42e-ccee6fb1ade5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Mzc0MzIsIm5iZiI6MTcxNDYzNzEzMiwicGF0aCI6Ii82NDkxNDg1LzMyNzM1MTMwNS1mM2RmYzFkOC0zMmIzLTRmOGEtYTQyZS1jY2VlNmZiMWFkZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMDgwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFlMGJjZDhmMzYyMjE0YTU4M2IyMGY1NzU5ZTU0ZTViMThmYjY1NzYwM2E1MjcwNTM3M2I0YzY0MmJhN2RlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TFhZ4hPr4Po9y53ESFNkX0W1Aaj8VIxBOTjlKcPmc2s">

On the other hand, if I try to discard the event in iOS, the plugin throws this exception:

<img width="757" alt="image" src="https://github.com/ebarooni/capacitor-calendar/assets/6491485/df99feee-5f6d-4626-9736-8007d6c8fd67">

Is this intended?

**Comment by ebarooni** [comment]
Hey @inpt333 thanks for the input. I will check and prioritize your feedback. About cancelling the prompt and getting an error, [this](https://github.com/ebarooni/capacitor-calendar/issues/69) issue is opened by another person already. I will pack all the fixes for the next release (6.2.0).

**Comment by ebarooni** [comment]
> > Hey @ebarooni , thanks for implementing this feature and releasing v6.1.0. It partially works for me in Android. The title is set properly, but the `startDate`, `endDate` and `isAllDay` are not properly applied, and I think the issue is that you're using the wrong Intent extras. These worked for me:
> > <img alt="image" width="764" src="https://private-user-images.githubusercontent.com/6491485/327351305-f3dfc1d8-32b3-4f8a-a42e-ccee6fb1ade5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Mzc0MzIsIm5iZiI6MTcxNDYzNzEzMiwicGF0aCI6Ii82NDkxNDg1LzMyNzM1MTMwNS1mM2RmYzFkOC0zMmIzLTRmOGEtYTQyZS1jY2VlNmZiMWFkZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMDgwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFlMGJjZDhmMzYyMjE0YTU4M2IyMGY1NzU5ZTU0ZTViMThmYjY1NzYwM2E1MjcwNTM3M2I0YzY0MmJhN2RlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TFhZ4hPr4Po9y53ESFNkX0W1Aaj8VIxBOTjlKcPmc2s">
> 
> On the other hand, if I try to discard the event in iOS, the plugin throws this exception:
> 
> <img alt="image" width="757" src="https://private-user-images.githubusercontent.com/6491485/327357713-df99feee-5f6d-4626-9736-8007d6c8fd67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzgzMDAsIm5iZiI6MTcxNDYzODAwMCwicGF0aCI6Ii82NDkxNDg1LzMyNzM1NzcxMy1kZjk5ZmVlZS01ZjZkLTQ2MjYtOTczNi04MDA3ZDZjOGZkNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMDgyMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM0MmFhMDZkNDQ2ZmY4Y2Y5ZDBmN2VhY2QzYzAyMTE3YjZkMzBlZTdkN2U4MTk5Y2E5MTMwMzlhOTBmNzk2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zgWMeEWg0VYuROLg71x0mV0KJ_vqzyRNhAcGiE08kEE">
> Is this intended?

Initially it was intended like this but from the feedbacks it seems to be not so helpful. It will change to returning an empty array.
