### ISSUE TITLE
createEventWithPrompt + isAllDay don't work properly on Android

### ISSUE THREAD

**Issue by inpt333** [ebarooni/capacitor-calendar#86]
As I commented here https://github.com/ebarooni/capacitor-calendar/pull/78/files#r1592106947 `createEventWithPrompt` on Android is expecting a boolean value for the extra `CalendarContract.EXTRA_EVENT_ALL_DAY`. With a number, the input is ignored by Google Calendar.

**Comment by ebarooni** [comment]
Hey thanks i will include the fix for this for the upcoming release
