### ISSUE TITLE
createEventWithPrompt() Event gets created correctly but plugin errors

### ISSUE THREAD

**Issue by filipelle** [ebarooni/capacitor-calendar#89]
Calling the function gets an event correctly added to the calendar, but it is not able to return the id array because of this error:
 
`EbarooniCapacitorCalendar/CapacitorCalendar.swift:347: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

here:
![image](https://github.com/ebarooni/capacitor-calendar/assets/44807059/ee2e3a67-6992-4ce2-ba78-2e90f380a56b)

wrapping the line with an if prevents the application from crashing but the code still throws an error.

------
I'm using capacitor 5 in an ionic angular application.

**Comment by nathanblankson** [comment]
It seems that I ran into this issue on iOS 17+ when I attempted to save an event through the prompt without the required read/write calendar permissions.

I am also using capacitor 5 in an ionic angular application 👋 

iOS 16.4

The modal is shown in a 'locked' state, so I cannot add the calendar event.

![image](https://github.com/ebarooni/capacitor-calendar/assets/35101840/3b063f38-3cb9-424c-91a5-3623f5613262)

iOS 17.0

- The modal is not shown in a locked state, allowing me to create the event.
- On doing so, the event is created and added to my calendar, and the app crashes.

![image](https://github.com/ebarooni/capacitor-calendar/assets/35101840/9b97f984-ea43-4f27-8030-3412b1fefdf7)

**Comment by filipelle** [comment]
@nathanblankson but the plugin's docs specify that for the prompt there is no need for permissions in ios. How did you solve the issue? thanks

**Comment by nathanblankson** [comment]
Hey @filipelle, there should be a section [here](https://github.com/ebarooni/capacitor-calendar/blob/main/ios/PERMISSIONS.md)

For iOS 17+, you will need to add to the `Info.plist` file the suitable permission key(s).

For me I have both `NSCalendarsFullAccessUsageDescription` for read/write to calendar and `NSRemindersFullAccessUsageDescription` for read/write to reminders.

I also have for iOS 16 and below `NSCalendarsUsageDescription`, `NSRemindersUsageDescription` and `NSContactsUsageDescription`.

Make sure to add both the key and description.

Before I call any `createEvent*` methods I make sure to call `CapacitorCalendar.requestAllPermissions()` which should show the prompt.

**Comment by ebarooni** [comment]
@nathanblankson @filipelle Hey both, im pretty sure and double checked the swift docs and it still says creating an event using prompt only requires the keys, but no explicit permission prompts. 

However reading closely, it seems to also write that the condition is only for iOS +17 and the app should not have the permission keys for below iOS 17. 

But finally im pretty sure i have tested it carefully before writing the docs. Can you both please write to me in detail about the state of all the permissions, keys, iOS version and etc. of your apps? My expectation was that the prompt will appear locked, only when the user was previously presented with a permissions prompt and the user explicitly rejected that.

With your input i will update the docs and/or fix the plugin if needed. 

Thanks!

**Comment by ebarooni** [comment]
@filipelle I was looking into the EKEvent source code and realized that the `eventIdentifier` is not optional and is always defined. Can you please share your swift, Xcode and Angular version? In my environment this is not producible. Also which iOS version are you testing on?

I have added the additional check for the `eventIdentifier`, however it seems to be redundant.
