### ISSUE TITLE
Problem updating events

### ISSUE THREAD

**Issue by matheusssoares** [ebarooni/capacitor-calendar#98]
Currently, the plugin does not have a method to update an event directly. To get around this, I successfully create an event and save the created event ID. When I need to update this event in my application, I pass the old event ID, remove this event, and try to create a new event with a new ID.

The problem is that, although the plugin indicates that the old event has been removed, it still appears in the event list. That is, the deleted event is not actually deleted from the visible list of events.

calendar used is from google.

**Comment by aparajita** [comment]
@matheusssoares How soon after deleting are you checking? It can take a minute or so for changes to show up in the google calendar.

**Comment by ebarooni** [comment]
@matheusssoares As @aparajita pointed out, it can take some time until the changes are made to the google calendar. Nevertheless, does the event get finally deleted? 

I will try to prioritise to implement updating events.

**Comment by matheusssoares** [comment]
@aparajita @ebarooni.
Thank you very much for your help, there really was a delay for synchronization, I resolved it temporarily by placing a load for a few seconds after removing the old event, and before opening the calendar and saving the new event in the calendar.

I wait for the update event to perform the migration. Very grateful for the help!
